import type { Metadata } from 'next'
import { Open_Sans, Play } from 'next/font/google'

import Layout from '@/components/layout/Layout'

import { Providers } from '@/providers/Providers'

import './globals.css'

const play = Play({
	variable: '--font-play',
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '700']
})

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
	weight: ['400', '700']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${play.variable} ${openSans.variable} antialiased`}>
				<Providers>
					<Layout>{children}</Layout>
				</Providers>
			</body>
		</html>
	)
}
